=== jah0006/1DAM_LMSGI_JAH/Tema11/Repaso Examen/repaso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="instrumento" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="familia" type="xs:string"></xs:element>
                            <xs:element name="stock" type="xs:integer"></xs:element>
                            <xs:element name="precio" type="xs:decimal">
                            </xs:element>
                            <xs:element name="caracteristicas" type="xs:string" minOccurs="0"></xs:element>
                            <xs:element name="comprador_frecuente" type="tipoCompradorFrecuente" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="ciudad" type="xs:string"></xs:attribute>
        </xs:complexType>
        
    </xs:element>
    <xs:simpleType name="tipoCompradorFrecuente">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== jah0006/1DAM_LMSGI_JAH/Tema11/Repaso Examen/repaso.xml
<?xml version="1.0" encoding="UTF-8"?>
<tienda ciudad="Madrid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repaso.xsd">

  <instrumento codigo="STRAT-001">
    <nombre>Fender Stratocaster</nombre>
    <familia>Cuerda</familia>
    <stock>12</stock>
    <precio>1250.50</precio>
    <caracteristicas>Electrica Madera Vintage</caracteristicas>
    <comprador_frecuente>12345678Z</comprador_frecuente>
  </instrumento>

  <instrumento codigo="SAX-99">
    <nombre>Saxofón Alto</nombre>
    <familia>Viento</familia>
    <stock>3</stock>
    <precio>890</precio>
    </instrumento>

</tienda>
